name: example
description: An example of how to use the SelectorWheel widget.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  selector_wheel:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
